gantt
    title 단길팀 프로젝트 일정
    todayMarker off
    dateFormat YYYY-MM-DD
    axisFormat  %m-%d

    section All
    요구사항 분석[완료]: 2024-03-14, 3d

    section Front-end
    와이어프레임생성[완료]: 2024-03-14, 7d
    EJS/CSS구현[완료]: 2024-03-21, 14d
    API연동: 2024-04-04, 14d

    section Back-end
    API명세서작성[완료]: 2024-03-21, 3d
    ERD셜계[완료]: 2024-03-24, 5d
    구글 클라우드 db연결[완료]: 2024-03-29, 1d
    회원가입기능 만들기: 2024-03-30, 4d
    로그인기능 시도: 2024-04-03, 2d
    지도웹페이지 출력: 2024-04-05, 1d
    리뷰작성기능: 2024-04-06, 1d
    리뷰삭제기능: 2024-04-07, 1d
    계정관리(이름변경): 2024-04-08, 1d
    계정관리(회원탈퇴): 2024-04-09, 1d
    계정관리(사진수정): 2024-04-10, 2d
    지도마커와 리뷰연결: 2024-04-12, 4d

%% 마무리까지 4/18 까지